# Generated by Django 6.0.3 on 2026-03-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('DUEÑO', 'Dueño de Cancha'), ('DEPORTISTA', 'Deportista')], default='DEPORTISTA', max_length=20),
        ),
    ]
